name: "Timelimit UI"
description: "Een add-on voor tijdslimiet beheer"
version: "1.0.5" # Let op: vergeet deze niet te verhogen bij de push
slug: "timelimit-ui"
arch:
  - aarch64
  - amd64
init: false
image: "ghcr.io/jeroenlind/timelimit-ui-{arch}"
ingress: true
ingress_port: 8099
panel_icon: "mdi:clock-check"
panel_title: "Timelimit"
ports:
  8099/tcp: 8099