name: "Timelimit UI"
description: "Een add-on voor tijdslimiet beheer"
version: "1.2.180"
slug: "timelimit-ui"
arch:
  - aarch64
  - amd64
init: false
image: "ghcr.io/jeroenlind/timelimit-ui-{arch}"
ingress: true
ingress_port: 8099
panel_icon: "mdi:clock-check"
panel_title: "Timelimit"
panel_admin: false
options:
  server_url: "http://192.168.68.30:8080"
schema:
  server_url: str