name: "Timelimit UI"
description: "WebUI app voor beheer van TimeLimit regels en synchronisatie"
version: "1.2.190"
slug: "timelimit-ui"
arch:
  - aarch64
  - amd64
init: false
image: "ghcr.io/jeroenlind/timelimit-ui-{arch}"
ingress: true
ingress_port: 8099
panel_icon: "mdi:clock-check"
panel_title: "Timelimit"
panel_admin: false
options:
  server_url: "http://192.168.68.30:8080"
  logging_mode: "standard"
schema:
  server_url: str
  logging_mode: list(standard|verbose)