name: TimeLimit UI
version: "0.1.1"
slug: timelimit-ui
description: Web UI for TimeLimit server (local or official)
url: "https://github.com/JeroenLind/timelimit-ui"
arch:
  - amd64
  - armv7
  - aarch64
startup: services
boot: auto
ingress: true
ingress_port: 3000
panel_icon: mdi:tablet-dashboard
panel_title: TimeLimit UI
options:
  server_url: "http://192.168.68.30:8080"
schema:
  server_url: str
environment:
  # wordt door HA gevuld, maar we mappen hem door naar de backend
  TIMELIMIT_SERVER_URL: "{server_url}"