name: "Timelimit UI"
description: "Een add-on voor tijdslimiet beheer"
version: "0.2.0"
slug: "timelimit-ui"
arch:
  - aarch64
  - amd64
  - armv7
init: false
# Forceer kleine letters in de URL: jeroenlind
image: "ghcr.io/jeroenlind/timelimit-ui-{arch}"